import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"
const inter = Inter({ subsets: ["latin"] });
import dbConnect from "@/config/db"
export const metadata: Metadata = {
  title: "Myunipixel",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  dbConnect()
  return (
    <html lang="en">
      <body>
        <header ><Header /></header>
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  )
}
